version: '3.8'
services:
  top-api:
    build: .
    container_name: top-api
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./.env:/opt/app/.env
    environment:
      - MONGO_LOGIN=${MONGO_LOGIN}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_HOST=mongo
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_AUTHDATABASE=${MONGO_AUTHDATABASE}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4.4
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - "27017:27017"
    volumes:
      - ./../mongo-data-4.4:/data/db